# Generated by Django 5.0.3 on 2024-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_government'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='about',
            field=models.CharField(max_length=300),
        ),
    ]
