# Generated by Django 5.0.3 on 2024-04-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_government_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='government',
            name='about',
            field=models.TextField(),
        ),
    ]
